let run = false,
    hours = 0,
    minutes = 0,
    nodesNumber = 0,
    currentGeneratingModel = '',
    minuteVsReal = 1000, //1000 - 24 минуты реального времени
    roadCoefs = [],
    timeObj = [
        {time: '00:00', coef: 0, description: ''},
        {time: '01:00', coef: 0, description: ''},
        {time: '02:00', coef: 0, description: ''},
        {time: '03:00', coef: 0, description: ''},
        {time: '04:00', coef: 0, description: ''},
        {time: '05:00', coef: 0, description: ''},
        {time: '06:00', coef: 0, description: ''},
        {time: '07:00', coef: 0, description: ''},
        {time: '08:00', coef: 0, description: ''},
        {time: '08:00', coef: 0, description: ''},
        {time: '10:00', coef: 0, description: ''},
        {time: '11:00', coef: 0, description: ''},
        {time: '12:00', coef: 0, description: ''},
        {time: '13:00', coef: 0, description: ''},
        {time: '14:00', coef: 0, description: ''},
        {time: '15:00', coef: 0, description: ''},
        {time: '16:00', coef: 0, description: ''},
        {time: '17:00', coef: 0, description: ''},
        {time: '18:00', coef: 0, description: ''},
        {time: '19:00', coef: 0, description: ''},
        {time: '20:00', coef: 0, description: ''},
        {time: '21:00', coef: 0, description: ''},
        {time: '22:00', coef: 0, description: ''},
        {time: '23:00', coef: 0, description: ''},
    ],
    carsInCity = 1000,
    edgeRefreshInterval = null,
    worldTimeout = null,
    tempModelParameters,
    canvasArray = [],
    wasFilled = false,
    canvasArrayInterval = null,
    roadTripTimeOut = null,
    roadAccidents = [
        {name: 'Авария', speedCoefNerf: 0.9, bandwidthCoefNerf: 0.87},
        {name: 'Ремонт дороги', speedCoefNerf: 0.95, bandwidthCoefNerf: 0.8},
        {name: 'Препятствие (поломанный автомобиль)', speedCoefNerf: 0.99, bandwidthCoefNerf: 0.9},
    ],
    qualityTypes = [
        {name: 'Очень хорошее', coef: 1, speedCoef: 1},
        {name: 'Хорошее', coef: 0.9, speedCoef: 0.95},
        {name: 'Среднее', coef: 0.65, speedCoef: 0.73},
        {name: 'Плохое', coef: 0.43, speedCoef: 0.52},
        {name: 'Очень плохое', coef: 0.24, speedCoef: 0.34},
    ],
    pavementTypes = [
        {name: 'Асфальтобетон', coef: 1, speedCoef: 1},
        {name: 'Цементобетон', coef: 0.9, speedCoef: 0.98},
        {name: 'Гравий', coef: 0.75, speedCoef: 0.86},
        {name: 'Щебенка', coef: 0.6, speedCoef: 0.74},
        {name: 'Грунт', coef: 0.5, speedCoef: 0.57},
    ],
    roadClasses = [
        {
            name: 'Автобан',
            description: 'Главная магистраль с ограниченным доступом, обычно с двумя или более полосами движения в каждую сторону с железобетонным парапетным ограждением на разделительной полосе.',
            minSpeed: 90,
            maxSpeed: 110,
            laneNumber: 8
        },
        {
            name: 'Трасса федерального значения',
            description: 'Самые важные дороги в системе страны, которые не являются автомагистралями. (Не обязательно разделены ограждением на разделительной полосе.)',
            minSpeed: 80,
            maxSpeed: 90,
            laneNumber: 6
        },
        {
            name: 'Дорога между большими городами',
            description: 'Важные дороги в системе страны. (Часто связывают крупные города.)',
            minSpeed: 80,
            maxSpeed: 90,
            laneNumber: 4
        },
        {
            name: 'Загородное шоссе',
            description: 'Дороги в системе страны. (Часто связывают города.)',
            minSpeed: 70,
            maxSpeed: 90,
            laneNumber: 2
        },
        {
            name: 'Дорога между маленькими поселениями',
            description: 'Дороги в системе страны. (Часто связывают небольшие города и деревни)',
            minSpeed: 60,
            maxSpeed: 80,
            laneNumber: 2
        },
        {
            name: 'Дорога без классификации',
            description: 'Наименее важные дороги в системе страны - то есть второстепенные дороги более низкой классификации, но которые служат цели, отличной от доступа к собственности. (Часто связывают деревни и деревни.)',
            minSpeed: 40,
            maxSpeed: 60,
            laneNumber: 2
        },
        {
            name: 'Уличная дорога',
            description: 'Дороги, которые служат доступом к жилью, без функции связывания населенных пунктов.',
            minSpeed: 40,
            maxSpeed: 60,
            laneNumber: 2
        },
    ],

    edgeNewParameters = {
        lane: null,
        quality: null
    },
    cars = [],
    bimodalIntensity = [
        {0: {'time': '0-1', 'coef': 0.08}},
        {1: {'time': '1-2', 'coef': 0.02}},
        {2: {'time': '2-3', 'coef': 0.01}},
        {3: {'time': '3-4', 'coef': 0.02}},
        {4: {'time': '4-5', 'coef': 0.06}},
        {5: {'time': '5-6', 'coef': 0.14}},
        {6: {'time': '6-7', 'coef': 0.52}},
        {7: {'time': '7-8', 'coef': 0.68}},
        {8: {'time': '8-9', 'coef': 0.99}},
        {9: {'time': '9-10', 'coef': 0.7}},
        {10: {'time': '10-11', 'coef': 0.5}},
        {11: {'time': '11-12', 'coef': 0.54}},
        {12: {'time': '12-13', 'coef': 0.6}},
        {13: {'time': '13-14', 'coef': 0.61}},
        {14: {'time': '14-15', 'coef': 0.43}},
        {15: {'time': '15-16', 'coef': 0.48}},
        {16: {'time': '16-17', 'coef': 0.93}},
        {17: {'time': '17-18', 'coef': 0.95}},
        {18: {'time': '18-19', 'coef': 0.79}},
        {19: {'time': '19-20', 'coef': 0.47}},
        {20: {'time': '20-21', 'coef': 0.26}},
        {21: {'time': '21-22', 'coef': 0.24}},
        {22: {'time': '22-23', 'coef': 0.19}},
        {23: {'time': '23-24', 'coef': 0.12}}
    ],
    unimodalIntensity = [
        {0: {'time': '0-1', 'coef': 0.08}},
        {1: {'time': '1-2', 'coef': 0.02}},
        {2: {'time': '2-3', 'coef': 0.01}},
        {3: {'time': '3-4', 'coef': 0.02}},
        {4: {'time': '4-5', 'coef': 0.06}},
        {5: {'time': '5-6', 'coef': 0.14}},
        {6: {'time': '6-7', 'coef': 0.52}},
        {7: {'time': '7-8', 'coef': 0.68}},
        {8: {'time': '8-9', 'coef': 0.99}},
        {9: {'time': '9-10', 'coef': 0.7}},
        {10: {'time': '10-11', 'coef': 0.5}},
        {11: {'time': '11-12', 'coef': 0.54}},
        {12: {'time': '12-13', 'coef': 0.6}},
        {13: {'time': '13-14', 'coef': 0.54}},
        {14: {'time': '14-15', 'coef': 0.43}},
        {15: {'time': '15-16', 'coef': 0.4}},
        {16: {'time': '16-17', 'coef': 0.37}},
        {17: {'time': '17-18', 'coef': 0.35}},
        {18: {'time': '18-19', 'coef': 0.32}},
        {19: {'time': '19-20', 'coef': 0.28}},
        {20: {'time': '20-21', 'coef': 0.26}},
        {21: {'time': '21-22', 'coef': 0.24}},
        {22: {'time': '22-23', 'coef': 0.19}},
        {23: {'time': '23-24', 'coef': 0.12}}
    ],
    modelToSave = {
        name: null,
        intensity: null,
        intensityName: null
    };